[build]
cmd = "cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"

[start]
cmd = "cd backend && gunicorn core.wsgi --bind 0.0.0.0:$PORT"

[env]
PYTHON_VERSION = "3.10"
